services:
  - type: web
    name: crypto-payment-processor
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    plan: free
    autoDeploy: true
    disk:
      name: crypto-payment-processor-disk
      mountPath: /app
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # Frontend URL for production (update with your actual domain)
      - key: FRONTEND_URL
        value: https://lightweight-crypto-payment-processor.onrender.com
      # Note: Add your actual environment variables in Render.com dashboard
      # SUPABASE_URL=https://your-project.supabase.co
      # SUPABASE_ANON_KEY=your-anon-key
      # SUPABASE_SERVICE_ROLE_KEY=your-service-role-key
      # UPSTASH_REDIS_REST_URL=https://your-redis.upstash.io
      # UPSTASH_REDIS_REST_TOKEN=your-redis-token
      # JWT_SECRET=your-jwt-secret
      # WEBHOOK_SECRET=your-webhook-secret
      # ANKR_API_KEY=your-ankr-key
      # BLOCKCYPHER_API_KEY=your-blockcypher-key
      # BLOCKSTREAM_API_KEY=your-blockstream-key
